# fly.toml app configuration file generated for skillwatch-service on 2024-07-08T13:55:34+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skillwatch-service'
primary_region = 'sin'
swap_size_mb = 512

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
