name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build the image
    runs-on: amateur-mega-disks
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/skillwatch:dev

  deploy:
    needs: build
    name: Deploy on render
    runs-on: amateur-mega-disks

    steps:
      - name: Deploy on Render
        run: |
          curl -sL ${{ secrets.RENDER_HOOK }}
